version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.2.1

workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          dockerfile: Dockerfile
          create-repo: true
          path: .
          repo: circleci-ecr-orb-demo
          tag: "$CIRCLE_SHA1"
